title: Slacker News
email: news@hackclub.com
description: Official news from Hack Club Slack.

permalink: /:slug/

# Build settings
theme: minima
sass:
  quiet_deps: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
